name: studley
favicon: null
layout_spectrum: 0.37849261052906513
typography_spectrum: 0.9936432698741555
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.38075734162703156
  lightness: 0.242091879947111
  saturation: 0.81957818265073
  rhythmicContrast: 0.820282866479829
purpose: []
